[tool.pytest.ini_options]
pythonpath = "."
testpaths = ["tests"]
python_files = ["test_*.py"]
markers = [
    "ui: UI component tests",
    "input: Input handling tests",
    "crud: CRUD operation tests",
    "validation: Input validation tests",
    "search: Search functionality tests"
]
